model_name: "muralone"
mass: 10.0
fluid_density: 998.0
control_method: 0
bounding_box:
  x: 0.356
  y: 0.338
  z: 0.25
center_of_mass:
  x: 0.68
  y: 0.585
  z: 0.865
center_of_volume:
  x: 0.68
  y: 0.585
  z: 0.865
buoyancy_adjustment: 0.05
thrusters:
  - x: 0.41 # Thruster 1
    y: 1.48
    z: 0.865
  - x: 0.948 # Thruster 2
    y: 1.48 
    z: 0.865
  - x: 0.68 # Thruster 3
    y: 0.585
    z: 0.865
