# Connect to the FCU (ArduSub) and pass messages to/from the GCS (QGroundControl, mavproxy)
#
# See https://github.com/mavlink/mavros/tree/ros2/mavros for connection schemas and defaults
#
#     udp://[bind_host][:port]@[remote_host[:port]][/?ids=sysid,compid]
#     udp default ports: 14555@14550
#
#     tcp://[server_host][:port][/?ids=sysid,compid]
#     tcp default port: 5760

mavros:
  ros__parameters:
    system_id: 255

    # /mavros/local_position/pose requires 2 plugins:
    #     imu handles the ATTITUDE_QUATERNION msg (MAV id 31)
    #     local_position handles the LOCAL_POSITION_NED msg (MAV id 32)
    # Also be sure to set the message interval to ~50ms for these 2 messages

    # The vision_pose plugin is provided by mavros_extras.
    # MAVROS will not complain if this package is missing.

    plugin_allowlist:
      - sys_status
      - command
      - imu
      - rc_io

      # --master=udp:0.0.0.0:14550 --out=udp:0.0.0.0:14660

mavros_node:
  ros__parameters:
    gcs_url: "udp://@192.168.2.2:14750"
