base_controller:
  ros__parameters:

    use_kalman: 1  # 1 for true, 0 for false
    use_pid: 1  # 1 for true, 0 for false

    # PWM settings
    neutral_pwm: 1500
    pwm_range: 50
    pwm_deadband: 5

    # PID parameters (using double)
    pid_kp: 1.2
    pid_ki: 0.3
    pid_kd: 0.4
    integral_clamp: 100.0

    # IMU calibration
    imu_surge_bias: 0.10787
    imu_gravity: 9.816

    # Kalman filter parameters
    kalman_process_noise: 0.05
    kalman_measurement_noise: 0.5
    kalman_estimated_error: 1.0
    kalman_initial_value: 0.0

    # Thresholds
    measurement_threshold: 0.05
    angular_threshold: 0.001

    depth_p_gain: 0.5
    depth_threshold: 0.1

    # Timing
    publish_rate_ms: 100
